name: Deploy Site
on:
  push:
    branches:
      - master

jobs:
  perform-deploy:
    name: Perform deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build static content
        run: uv run --directory site/ pelican content

      - name: Upload static content as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/output/
